# Production Configuration
# Balanced performance and resource usage for production deployments

protein_encoder_type: esm
drug_encoder_type: gin
use_fusion: true
device: auto
seed: 42
verbose: true
log_level: INFO

protein_config:
  output_dim: 128
  max_length: 200
  model_name: facebook/esm2_t6_8M_UR50D
  freeze_initial: true

drug_config:
  output_dim: 128
  node_features: 78
  hidden_dim: 128
  num_layers: 5
  dropout: 0.2
  use_batch_norm: true

fusion_config:
  hidden_dim: 256
  num_heads: 8

predictor_config:
  hidden_dims: [512, 256]
  dropout: 0.3
  activation: relu

training_config:
  batch_size: 4
  learning_rate_phase1: 0.001
  learning_rate_phase2: 0.0001
  num_epochs_phase1: 50
  num_epochs_phase2: 30
  weight_decay: 0.00001
  early_stopping_patience: 10
  checkpoint_interval: 5
  gradient_clip_norm: 1.0
  max_memory_mb: 4000
  enable_gradient_checkpointing: true
  memory_monitoring_interval: 10
  aggressive_memory_cleanup: false

data_config:
  datasets: [kiba, davis, bindingdb]
  data_dir: data
  max_protein_length: 200
  validation_split: 0.1
  test_split: 0.1
  num_workers: 4
  pin_memory: true